import { WordItem, KanjiItem } from './types';

export const INITIAL_WORDS: WordItem[] = [
  {
    id: 'w1',
    kanji: '開ける',
    reading: 'あける',
    meaning: 'mở (cửa, nắp, hộp...)',
    partOfSpeech: 'Verb 2, tha động từ',
    level: 'N5',
    hanViet: '開 KHAI',
    exampleJa: '窓を開けてください。',
    exampleRuby: [
      { text: '窓', ruby: 'まど' },
      { text: 'を' },
      { text: '開', ruby: 'あ' },
      { text: 'けてください。' },
    ],
    exampleVi: 'Xin hãy mở cửa sổ.',
    createdAt: '2026-08-20',
    reviewCount: 8,
    correctStreak: 4,
    nextDueDate: 'Hôm nay',
  },
  {
    id: 'w2',
    kanji: '勉強',
    reading: 'べんきょう',
    meaning: 'sự học tập, nghiên cứu',
    partOfSpeech: 'Noun, する verb',
    level: 'N5',
    hanViet: '勉 MIỄN · 強 CƯỜNG',
    exampleJa: '毎日一時間、日本語を勉強しています。',
    exampleRuby: [
      { text: '毎日', ruby: 'まいにち' },
      { text: '一時間', ruby: 'いちじかん' },
      { text: '、' },
      { text: '日本語', ruby: 'にほんご' },
      { text: 'を' },
      { text: '勉強', ruby: 'べんきょう' },
      { text: 'しています。' },
    ],
    exampleVi: 'Mỗi ngày tôi học tiếng Nhật một tiếng.',
    createdAt: '2026-08-21',
    reviewCount: 12,
    correctStreak: 6,
    nextDueDate: 'Hôm nay',
  },
  {
    id: 'w3',
    kanji: '静か',
    reading: 'しずか',
    meaning: 'yên tĩnh, thanh bình',
    partOfSpeech: 'Na-adjective',
    level: 'N5',
    hanViet: '静 TĨNH',
    exampleJa: 'この図書館はとても静かです。',
    exampleRuby: [
      { text: 'この' },
      { text: '図書館', ruby: 'としょかん' },
      { text: 'はとても' },
      { text: '静', ruby: 'しず' },
      { text: 'かです。' },
    ],
    exampleVi: 'Thư viện này rất yên tĩnh.',
    createdAt: '2026-08-23',
    reviewCount: 5,
    correctStreak: 3,
    nextDueDate: 'Hôm nay',
  },
  {
    id: 'w4',
    kanji: '約束',
    reading: 'やくそく',
    meaning: 'lời hứa, cuộc hẹn',
    partOfSpeech: 'Noun, する verb',
    level: 'N4',
    hanViet: '約 ƯỚC · 束 THÚC',
    exampleJa: '友達と約束をしました。',
    exampleRuby: [
      { text: '友達', ruby: 'ともだち' },
      { text: 'と' },
      { text: '約束', ruby: 'やくそく' },
      { text: 'をしました。' },
    ],
    exampleVi: 'Tôi đã hẹn với bạn.',
    createdAt: '2026-08-25',
    reviewCount: 7,
    correctStreak: 2,
    nextDueDate: 'Hôm nay',
  },
  {
    id: 'w5',
    kanji: '懐かしい',
    reading: 'なつかしい',
    meaning: 'thấy nhớ, gợi nhớ hoài niệm',
    partOfSpeech: 'I-adjective',
    level: 'N3',
    hanViet: '懐 HOÀI',
    exampleJa: 'この歌は懐かしいですね。',
    exampleRuby: [
      { text: 'この' },
      { text: '歌', ruby: 'うた' },
      { text: 'は' },
      { text: '懐', ruby: 'なつ' },
      { text: 'かしいですね。' },
    ],
    exampleVi: 'Bài hát này gợi nhớ quá nhỉ.',
    createdAt: '2026-08-28',
    reviewCount: 9,
    correctStreak: 5,
    nextDueDate: 'Ngày mai',
  },
  {
    id: 'w6',
    kanji: 'ゆっくり',
    reading: 'ゆっくり',
    meaning: 'chậm rãi, thong thả, từ từ',
    partOfSpeech: 'Adverb',
    level: 'N5',
    hanViet: '—',
    exampleJa: 'ゆっくり話してください。',
    exampleRuby: [
      { text: 'ゆっくり' },
      { text: '話', ruby: 'はな' },
      { text: 'してください。' },
    ],
    exampleVi: 'Xin hãy nói chậm lại.',
    createdAt: '2026-08-30',
    reviewCount: 4,
    correctStreak: 4,
    nextDueDate: 'Ngày mai',
  },
  {
    id: 'w7',
    kanji: '開始',
    reading: 'かいし',
    meaning: 'bắt đầu, khởi đầu',
    partOfSpeech: 'Noun, する verb',
    level: 'N3',
    hanViet: '開 KHAI · 始 THỦY',
    exampleJa: '会議は十時に開始されます。',
    exampleRuby: [
      { text: '会議', ruby: 'かいぎ' },
      { text: 'は' },
      { text: '十時', ruby: 'じゅうじ' },
      { text: 'に' },
      { text: '開始', ruby: 'かいし' },
      { text: 'されます。' },
    ],
    exampleVi: 'Cuộc họp sẽ bắt đầu lúc 10 giờ.',
    createdAt: '2026-09-01',
    reviewCount: 3,
    correctStreak: 2,
    nextDueDate: 'Hôm nay',
  },
  {
    id: 'w8',
    kanji: '予約',
    reading: 'よやく',
    meaning: 'đặt trước, hẹn trước (vé, phòng, bàn...)',
    partOfSpeech: 'Noun, する verb',
    level: 'N4',
    hanViet: '予 DỰ · 約 ƯỚC',
    exampleJa: '新幹線の切符を予約しました。',
    exampleRuby: [
      { text: '新幹線', ruby: 'しんかんせん' },
      { text: 'の' },
      { text: '切符', ruby: 'きっぷ' },
      { text: 'を' },
      { text: '予約', ruby: 'よやく' },
      { text: 'しました。' },
    ],
    exampleVi: 'Tôi đã đặt trước vé tàu Shinkansen.',
    createdAt: '2026-09-02',
    reviewCount: 6,
    correctStreak: 5,
    nextDueDate: 'Hôm nay',
  },
];

export const INITIAL_KANJI: KanjiItem[] = [
  {
    character: '開',
    hanViet: 'KHAI',
    meaning: 'Mở, bắt đầu',
    level: 'N5',
    wordIds: ['w1', 'w7'],
  },
  {
    character: '勉',
    hanViet: 'MIỄN',
    meaning: 'Cố gắng, nỗ lực',
    level: 'N5',
    wordIds: ['w2'],
  },
  {
    character: '強',
    hanViet: 'CƯỜNG',
    meaning: 'Mạnh mẽ, kiên cố',
    level: 'N5',
    wordIds: ['w2'],
  },
  {
    character: '静',
    hanViet: 'TĨNH',
    meaning: 'Yên lặng, tĩnh mịch',
    level: 'N5',
    wordIds: ['w3'],
  },
  {
    character: '約',
    hanViet: 'ƯỚC',
    meaning: 'Hứa hẹn, ước định, tóm lược',
    level: 'N4',
    wordIds: ['w4', 'w8'],
  },
  {
    character: '束',
    hanViet: 'THÚC',
    meaning: 'Buộc lại, bó, gò bó',
    level: 'N4',
    wordIds: ['w4'],
  },
  {
    character: '懐',
    hanViet: 'HOÀI',
    meaning: 'Tấm lòng, hoài niệm, ôm ấp',
    level: 'N3',
    wordIds: ['w5'],
  },
  {
    character: '始',
    hanViet: 'THỦY',
    meaning: 'Ban đầu, bắt đầu',
    level: 'N4',
    wordIds: ['w7'],
  },
  {
    character: '予',
    hanViet: 'DỰ',
    meaning: 'Trước, dự liệu',
    level: 'N4',
    wordIds: ['w8'],
  },
];

// Offline dictionary database for Screen B (Add a word) instant auto-fill
export const AUTOFILL_DICTIONARY: Record<string, Partial<WordItem>> = {
  '開ける': {
    reading: 'あける',
    meaning: 'mở',
    partOfSpeech: 'Verb 2, tha động từ',
    level: 'N5',
    hanViet: '開 KHAI',
    exampleJa: '窓を開けてください。',
    exampleVi: 'Xin hãy mở cửa sổ.',
  },
  '開く': {
    reading: 'ひらく',
    meaning: 'mở ra, nở (hoa)',
    partOfSpeech: 'Verb 1, tự/tha động từ',
    level: 'N4',
    hanViet: '開 KHAI',
    exampleJa: 'ドアが開きます。',
    exampleVi: 'Cửa đang mở.',
  },
  '勉強': {
    reading: 'べんきょう',
    meaning: 'sự học tập',
    partOfSpeech: 'Noun, N5',
    level: 'N5',
    hanViet: '勉 MIỄN · 強 CƯỜNG',
    exampleJa: '毎日一時間、日本語を勉強しています。',
    exampleVi: 'Mỗi ngày tôi học tiếng Nhật một tiếng.',
  },
  '静か': {
    reading: 'しずか',
    meaning: 'yên tĩnh',
    partOfSpeech: 'Na-adjective',
    level: 'N5',
    hanViet: '静 TĨNH',
    exampleJa: 'この図書館はとても静かです。',
    exampleVi: 'Thư viện này rất yên tĩnh.',
  },
  '約束': {
    reading: 'やくそく',
    meaning: 'lời hứa, cuộc hẹn',
    partOfSpeech: 'Noun',
    level: 'N4',
    hanViet: '約 ƯỚC · 束 THÚC',
    exampleJa: '友達と約束をしました。',
    exampleVi: 'Tôi đã hẹn với bạn.',
  },
  '懐かしい': {
    reading: 'なつかしい',
    meaning: 'thấy nhớ, hoài niệm',
    partOfSpeech: 'I-adjective',
    level: 'N3',
    hanViet: '懐 HOÀI',
    exampleJa: 'この歌は懐かしいですね。',
    exampleVi: 'Bài hát này gợi nhớ quá nhỉ.',
  },
  '食べる': {
    reading: 'たべる',
    meaning: 'ăn',
    partOfSpeech: 'Verb 2',
    level: 'N5',
    hanViet: '食 THỰC',
    exampleJa: '朝ご飯を食べましたか。',
    exampleVi: 'Bạn đã ăn bữa sáng chưa?',
  },
  '飲む': {
    reading: 'のむ',
    meaning: 'uống',
    partOfSpeech: 'Verb 1',
    level: 'N5',
    hanViet: '飲 ẨM',
    exampleJa: 'お茶を飲みましょう。',
    exampleVi: 'Chúng ta cùng uống trà nhé.',
  },
  '行く': {
    reading: 'いく',
    meaning: 'đi',
    partOfSpeech: 'Verb 1',
    level: 'N5',
    hanViet: '行 HÀNH',
    exampleJa: '東京へ行きます。',
    exampleVi: 'Tôi đi Tokyo.',
  },
};
